
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxsqmsmsnxgmenovnfrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4c3Ftc21zbnhnbWVub3ZuZnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NzM1NTksImV4cCI6MjA2MzM0OTU1OX0.FtYGOTlq6lFnFtJRS6gpf3wg3PJUvKt9-irLes7SeJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with more resilient configuration
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        'x-application-name': 'learn-stride-online',
      },
    },
    // Add better timeout and retry settings
    db: {
      schema: 'public',
    },
  }
);

